language: node_js
node_js:
    - "5.3"
    - "5.0"
    - "4.2"
    - "4.0"

before_install:
    - cp test/config/options.json.sample test/config/options.json
    - perl -pi -e "s/WEBPAGETEST_API_KEY/$WEBPAGETEST_API_KEY/g" test/config/options.json
